# Generated by Django 5.0.6 on 2026-06-05 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='项目名称')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='项目别名')),
                ('description', models.TextField(verbose_name='项目简介')),
                ('content', models.TextField(verbose_name='详细说明(Markdown)')),
                ('cover_image', models.URLField(blank=True, max_length=255, null=True, verbose_name='封面图片')),
                ('tech_stack', models.CharField(blank=True, max_length=255, null=True, verbose_name='技术栈')),
                ('github_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='GitHub链接')),
                ('demo_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='演示地址')),
                ('video_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='演示视频')),
                ('status', models.IntegerField(choices=[(0, '草稿'), (1, '已发布'), (2, '隐藏')], default=0, verbose_name='状态')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞次数')),
                ('favorite_count', models.IntegerField(default=0, verbose_name='收藏次数')),
                ('difficulty', models.IntegerField(blank=True, choices=[(1, '入门'), (2, '中级'), (3, '高级')], null=True, verbose_name='难度等级')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='完成日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'project_tags',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='标签名称')),
                ('slug', models.SlugField(max_length=30, unique=True, verbose_name='标签别名')),
                ('color', models.CharField(default='#409EFF', max_length=10, verbose_name='标签颜色')),
                ('type', models.IntegerField(choices=[(1, '项目'), (2, '文章'), (3, '笔记'), (4, '通用')], default=4, verbose_name='类型')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('slug', models.SlugField(verbose_name='分类别名')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='分类描述')),
                ('type', models.IntegerField(choices=[(1, '项目'), (2, '文章'), (3, '笔记')], default=1, verbose_name='类型')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='图标')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.category', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'db_table': 'categories',
            },
        ),
    ]
