# Generated by Django 5.0.6 on 2026-06-05 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.category', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='projecttag',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tags', to='projects.project'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['type'], name='tags_type_8382fc_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['usage_count'], name='tags_usage_c_26dec2_idx'),
        ),
        migrations.AddField(
            model_name='projecttag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tags', to='projects.tag'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(related_name='projects', through='projects.ProjectTag', to='projects.tag', verbose_name='标签'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['type'], name='categories_type_735b1a_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='categories_parent__7983b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('slug', 'type')},
        ),
        migrations.AddIndex(
            model_name='projecttag',
            index=models.Index(fields=['project'], name='project_tag_project_436b32_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttag',
            index=models.Index(fields=['tag'], name='project_tag_tag_id_e3e3bd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projecttag',
            unique_together={('project', 'tag')},
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['category'], name='projects_categor_c363bc_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['author'], name='projects_author__4b86ac_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='projects_status_6303d7_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_featured'], name='projects_is_feat_5ab0be_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['published_at'], name='projects_publish_dff618_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['view_count'], name='projects_view_co_788ee9_idx'),
        ),
    ]
