# Generated by Django 5.0.6 on 2026-06-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='文章标题')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='文章别名')),
                ('summary', models.CharField(blank=True, max_length=500, null=True, verbose_name='文章摘要')),
                ('content', models.TextField(verbose_name='文章内容(Markdown)')),
                ('cover_image', models.URLField(blank=True, max_length=255, null=True, verbose_name='封面图片')),
                ('reading_time', models.IntegerField(default=0, verbose_name='阅读时间(分钟)')),
                ('word_count', models.IntegerField(default=0, verbose_name='字数')),
                ('status', models.IntegerField(choices=[(0, '草稿'), (1, '已发布'), (2, '隐藏')], default=0, verbose_name='状态')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('is_top', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('allow_comment', models.BooleanField(default=True, verbose_name='允许评论')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞次数')),
                ('favorite_count', models.IntegerField(default=0, verbose_name='收藏次数')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论次数')),
                ('source_type', models.IntegerField(blank=True, choices=[(1, '原创'), (2, '翻译'), (3, '转载')], null=True, verbose_name='来源类型')),
                ('source_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='原文链接')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'articles',
            },
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'article_tags',
            },
        ),
    ]
