# Generated by Django 5.0.6 on 2026-06-05 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='projects.category', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='articletag',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_tags', to='articles.article'),
        ),
        migrations.AddField(
            model_name='articletag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_tags', to='projects.tag'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='articles', through='articles.ArticleTag', to='projects.tag', verbose_name='标签'),
        ),
        migrations.AddIndex(
            model_name='articletag',
            index=models.Index(fields=['article'], name='article_tag_article_30f1a8_idx'),
        ),
        migrations.AddIndex(
            model_name='articletag',
            index=models.Index(fields=['tag'], name='article_tag_tag_id_868b34_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='articletag',
            unique_together={('article', 'tag')},
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category'], name='articles_categor_11f3b8_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['author'], name='articles_author__a0ff4a_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status'], name='articles_status_a4f178_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_featured'], name='articles_is_feat_9387e0_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_top'], name='articles_is_top_f79293_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['published_at'], name='articles_publish_73ad5f_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['view_count'], name='articles_view_co_be2bb6_idx'),
        ),
    ]
