-- ============================================
-- Learning Web Site - Database Initialization
-- Database: learning_web
-- ============================================

CREATE DATABASE IF NOT EXISTS learning_web
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

USE learning_web;

-- ============================================
-- Default Data
-- ============================================

-- Admin user (password: admin123, generated by Django)
-- NOTE: This is a placeholder; use `python manage.py createsuperuser` in production
-- INSERT INTO users (username, password, email, nickname, role, status)
-- VALUES ('admin', 'pbkdf2_sha256$...', 'admin@example.com', '管理员', 1, 1);

-- Default categories
INSERT INTO categories (name, slug, type, sort_order) VALUES
('前端开发', 'frontend', 1, 1),
('后端开发', 'backend', 1, 2),
('全栈项目', 'fullstack', 1, 3),
('技术教程', 'tutorial', 2, 1),
('经验分享', 'experience', 2, 2),
('学习笔记', 'learning', 3, 1);

-- Default tags
INSERT INTO tags (name, slug, color, type) VALUES
('Vue', 'vue', '#42b883', 4),
('Django', 'django', '#092e20', 4),
('MySQL', 'mysql', '#00758f', 4),
('Redis', 'redis', '#dc382d', 4),
('Docker', 'docker', '#2496ed', 4),
('Python', 'python', '#3776ab', 4),
('JavaScript', 'javascript', '#f7df1e', 4);

-- Default system settings
INSERT INTO settings (`key`, value, description, is_public) VALUES
('site_name', '我的学习成果展示', '网站名称', 1),
('site_description', '记录学习历程，分享技术知识', '网站描述', 1),
('site_keywords', 'Vue, Django, 学习, 技术', '网站关键词', 1),
('allow_comment', 'true', '是否允许评论', 1),
('comment_need_review', 'true', '评论是否需要审核', 0);
