# Generated by Django 5.0.6 on 2026-06-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='笔记标题')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='笔记别名')),
                ('content', models.TextField(verbose_name='笔记内容(Markdown)')),
                ('learning_stage', models.IntegerField(choices=[(1, '入门'), (2, '进阶'), (3, '精通')], default=1, verbose_name='学习阶段')),
                ('progress', models.IntegerField(default=0, verbose_name='学习进度(0-100)')),
                ('difficulty', models.IntegerField(blank=True, choices=[(1, '入门'), (2, '中级'), (3, '高级')], null=True, verbose_name='难度等级')),
                ('status', models.IntegerField(choices=[(0, '草稿'), (1, '已发布')], default=0, verbose_name='状态')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞次数')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '学习笔记',
                'verbose_name_plural': '学习笔记',
                'db_table': 'notes',
            },
        ),
        migrations.CreateModel(
            name='NoteTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'note_tags',
            },
        ),
    ]
