# Generated by Django 5.0.6 on 2026-06-05 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='projects.category', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='note',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='notes.note', verbose_name='父笔记'),
        ),
        migrations.AddField(
            model_name='notetag',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_tags', to='notes.note'),
        ),
        migrations.AddField(
            model_name='notetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_tags', to='projects.tag'),
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(related_name='notes', through='notes.NoteTag', to='projects.tag', verbose_name='标签'),
        ),
        migrations.AddIndex(
            model_name='notetag',
            index=models.Index(fields=['note'], name='note_tags_note_id_286136_idx'),
        ),
        migrations.AddIndex(
            model_name='notetag',
            index=models.Index(fields=['tag'], name='note_tags_tag_id_d557f2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notetag',
            unique_together={('note', 'tag')},
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['category'], name='notes_categor_07ce8b_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['author'], name='notes_author__04d296_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['learning_stage'], name='notes_learnin_a7da32_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['parent'], name='notes_parent__367800_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['status'], name='notes_status_c41bea_idx'),
        ),
    ]
