# Generated by Django 5.0.6 on 2026-06-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.IntegerField(choices=[(1, '文章'), (2, '项目'), (3, '笔记')], verbose_name='收藏对象类型')),
                ('object_id', models.BigIntegerField(verbose_name='收藏对象ID')),
                ('folder_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='收藏夹名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'db_table': 'favorites',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.IntegerField(choices=[(1, '文章'), (2, '项目'), (3, '笔记'), (4, '评论')], verbose_name='点赞对象类型')),
                ('object_id', models.BigIntegerField(verbose_name='点赞对象ID')),
                ('anonymous_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='匿名标识')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '点赞',
                'verbose_name_plural': '点赞',
                'db_table': 'likes',
            },
        ),
    ]
