# Generated by Django 5.0.6 on 2026-06-05 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('content_type', models.IntegerField(choices=[(1, '文章'), (2, '项目'), (3, '笔记')], verbose_name='评论对象类型')),
                ('object_id', models.BigIntegerField(verbose_name='评论对象ID')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='访客昵称')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='访客邮箱')),
                ('website', models.URLField(blank=True, max_length=255, null=True, verbose_name='访客网站')),
                ('status', models.IntegerField(choices=[(0, '待审核'), (1, '已发布'), (2, '已拒绝')], default=0, verbose_name='状态')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment', verbose_name='父评论')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'comments',
            },
        ),
    ]
