# Generated by Django 5.0.6 on 2026-06-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='会话ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户代理')),
                ('referer', models.URLField(blank=True, max_length=255, null=True, verbose_name='来源页面')),
                ('request_url', models.CharField(max_length=255, verbose_name='访问URL')),
                ('request_method', models.CharField(max_length=10, verbose_name='请求方法')),
                ('response_status', models.IntegerField(blank=True, null=True, verbose_name='响应状态码')),
                ('content_type', models.IntegerField(blank=True, null=True, verbose_name='内容类型')),
                ('object_id', models.BigIntegerField(blank=True, null=True, verbose_name='内容对象ID')),
                ('device_type', models.IntegerField(blank=True, choices=[(1, 'PC'), (2, '移动端'), (3, '平板')], null=True, verbose_name='设备类型')),
                ('browser', models.CharField(blank=True, max_length=50, null=True, verbose_name='浏览器')),
                ('os', models.CharField(blank=True, max_length=50, null=True, verbose_name='操作系统')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='国家')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='城市')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='停留时间(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='访问时间')),
            ],
            options={
                'verbose_name': '访问日志',
                'verbose_name_plural': '访问日志',
                'db_table': 'visit_logs',
            },
        ),
    ]
