# Generated by Django 5.0.6 on 2026-06-05 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('statistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visitlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddIndex(
            model_name='visitlog',
            index=models.Index(fields=['user'], name='visit_logs_user_id_b97305_idx'),
        ),
        migrations.AddIndex(
            model_name='visitlog',
            index=models.Index(fields=['ip_address'], name='visit_logs_ip_addr_c48427_idx'),
        ),
        migrations.AddIndex(
            model_name='visitlog',
            index=models.Index(fields=['request_url'], name='visit_logs_request_40ee8b_idx'),
        ),
        migrations.AddIndex(
            model_name='visitlog',
            index=models.Index(fields=['content_type', 'object_id'], name='visit_logs_content_daf464_idx'),
        ),
        migrations.AddIndex(
            model_name='visitlog',
            index=models.Index(fields=['created_at'], name='visit_logs_created_191ce1_idx'),
        ),
        migrations.AddIndex(
            model_name='visitlog',
            index=models.Index(fields=['device_type'], name='visit_logs_device__2b32ae_idx'),
        ),
    ]
